// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: currency_converter.proto

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CurrencyConverterClient is the client API for CurrencyConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyConverterClient interface {
	ConvertCurrency(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionResponse, error)
}

type currencyConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyConverterClient(cc grpc.ClientConnInterface) CurrencyConverterClient {
	return &currencyConverterClient{cc}
}

func (c *currencyConverterClient) ConvertCurrency(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionResponse, error) {
	out := new(ConversionResponse)
	err := c.cc.Invoke(ctx, "/CurrencyConverter/ConvertCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyConverterServer is the server API for CurrencyConverter service.
// All implementations must embed UnimplementedCurrencyConverterServer
// for forward compatibility
type CurrencyConverterServer interface {
	ConvertCurrency(context.Context, *ConversionRequest) (*ConversionResponse, error)
	mustEmbedUnimplementedCurrencyConverterServer()
}

// UnimplementedCurrencyConverterServer must be embedded to have forward compatible implementations.
type UnimplementedCurrencyConverterServer struct {
}

func (UnimplementedCurrencyConverterServer) ConvertCurrency(context.Context, *ConversionRequest) (*ConversionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertCurrency not implemented")
}
func (UnimplementedCurrencyConverterServer) mustEmbedUnimplementedCurrencyConverterServer() {}

// UnsafeCurrencyConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyConverterServer will
// result in compilation errors.
type UnsafeCurrencyConverterServer interface {
	mustEmbedUnimplementedCurrencyConverterServer()
}

func RegisterCurrencyConverterServer(s grpc.ServiceRegistrar, srv CurrencyConverterServer) {
	s.RegisterService(&CurrencyConverter_ServiceDesc, srv)
}

func _CurrencyConverter_ConvertCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).ConvertCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CurrencyConverter/ConvertCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).ConvertCurrency(ctx, req.(*ConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyConverter_ServiceDesc is the grpc.ServiceDesc for CurrencyConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CurrencyConverter",
	HandlerType: (*CurrencyConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertCurrency",
			Handler:    _CurrencyConverter_ConvertCurrency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency_converter.proto",
}
